### ISSUE TITLE
Story - Text column width

### ISSUE THREAD

**Issue by agentdoublel** [tfuqua/whitehouserolls#27]
### Location
Our Story, Text areas

### Description
Does the text take up 7 columns? Body text should be 6 and quotes should be 10
Also can you confirm that the lineheight is 35px?

### Screenshot
<img width="1022" alt="screen shot 2016-11-01 at 1 31 02 pm" src="https://cloud.githubusercontent.com/assets/17103891/19899726/7f482f08-a037-11e6-9862-d21db4dc9ab6.png">

**Comment by tfuqua** [comment]
Updated the line height to 35px.

So if we were to create the content at 7 columns wide out of 12 that would leave 3 and 2 remaining and the content would then be off-center. I will update the content to 8 columns.

Since the blockquote is part of the 8 column content it is tough to have it stretch wider, if this is vital we might need to rethink how we build the content slightly.
